# Numpy 

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a[0]

1

In [4]:
a[1:4]

array([2, 3, 4])

# Memory aloocation for list V/S numpy array

1 . List

In [10]:
import sys
l = range(1000)
print(sys.getsizeof(1) * len(l))

28000


2 . Numpy array

In [9]:
array = np.arange(1000)
print(array.size * array.itemsize)

4000


# Speed between list V/S numpy array 

In [13]:
import time

In [20]:
size = 10000

1 . List

In [21]:
l1 = range(size)
l2 = range(size)
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("Time :", (time.time() - start) * 1000)

Time : 1.9989013671875


2 . Numpy array

In [22]:
a1 = np.arange(size)
a2 = np.arange(size)
start = time.time()
result_1 = a1 + a2
print("Time :", (time.time() - start) * 1000)

Time : 0.9698867797851562


# mathematical operations

In [24]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([3,5,6,7,8])

In [25]:
a1 + a2

array([ 4,  7,  9, 11, 13])

In [26]:
a1 - a2

array([-2, -3, -3, -3, -3])

In [27]:
a1 * a2

array([ 3, 10, 18, 28, 40])

In [28]:
a1 / a2

array([0.33333333, 0.4       , 0.5       , 0.57142857, 0.625     ])

In [29]:
a1 % a2

array([1, 2, 3, 4, 5])

In [31]:
a1.itemsize     # Size of each element in array

4

In [33]:
a1.dtype      # data type of array

dtype('int32')

In [34]:
a1.ndim     # dimension of array

1

In [36]:
a = np.array([[1,2,3,4,5],[3,4,5,6,7]])
a

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [38]:
a.ndim     # 2 dimensional array

2

In [39]:
a = np.array([[1,2,3],[3,4,5]],dtype=np.float64)
a

array([[1., 2., 3.],
       [3., 4., 5.]])

In [42]:
a.dtype         # Explicitly defining data type of array

dtype('float64')

In [41]:
a.itemsize

8

In [44]:
a.size        # Total element of the array

6

In [46]:
a.shape      # row and column of the array

(2, 3)

# Placeholders

In [48]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [51]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [52]:
a = np.array([[1,2,3,4],[3,4,5,6]])
a

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [53]:
a.shape

(2, 4)

In [57]:
a.reshape(4,2)         # Reshape the array's row and column

array([[1, 2],
       [3, 4],
       [3, 4],
       [5, 6]])

# Aggregate functions

In [58]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
a.min()

1

In [60]:
a.max()

8

In [61]:
a.mean()

4.5

In [62]:
a.sum()

36

In [63]:
a.sum(axis=0)

array([ 6,  8, 10, 12])

In [64]:
a.sum(axis=1)

array([10, 26])

In [66]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [67]:
np.std(a)

2.29128784747792

# Indexing

In [69]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [71]:
b = np.arange(8).reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [72]:
a[1]

array([3, 4, 5])

In [73]:
a[1,0]

3

In [74]:
a[:,0:1]

array([[0],
       [3]])

In [75]:
for row in a:
    print(row)

[0 1 2]
[3 4 5]


In [76]:
for row in a.flat:
    print(row)            # flat is used to gave aray in 1 line

0
1
2
3
4
5


# Boolean indexing

In [78]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
b = a > 4
b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [80]:
a[b]

array([5, 6, 7, 8])

In [82]:
a[b] = 1111
a

array([[   0,    1,    2],
       [   3,    4, 1111],
       [1111, 1111, 1111]])

# Combining array

In [83]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [86]:
b = np.arange(6).reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [88]:
np.vstack((a,b))      # VERTICAL COMBINING

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [90]:
np.hstack((a,b))          #HORIZONTAL COMBINING

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

# Splitting Array

In [92]:
a = np.arange(30).reshape(10,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [99]:
split = np.vsplit(a,2)
split                           # Default takes verticalsplitting

[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]])]

In [95]:
split[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [96]:
split[1]

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [103]:
split = np.hsplit(a,3)
split                     # Horizontal splitting

[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18],
        [21],
        [24],
        [27]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16],
        [19],
        [22],
        [25],
        [28]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17],
        [20],
        [23],
        [26],
        [29]])]

In [102]:
split[0]

array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18],
       [21],
       [24],
       [27]])

In [106]:
a.ravel()      # Change array into 1 dimension

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])