In [3]:
import numpy as np

## Declare a numpy array

In [10]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [64]:
b = np.array([3,4,5,6],dtype=np.float64)
b

array([3., 4., 5., 6.])

# Numpy array attributes

In [3]:
a.dtype

dtype('int32')

In [4]:
a.shape

(4,)

In [6]:
a.ndim

1

In [7]:
a.itemsize

4

In [11]:
a.size

5

In [13]:
a.strides

(4,)

In [14]:
b = np.array([6,7,8,9,0])
b

array([6, 7, 8, 9, 0])

# Numpy array mathematical operation

In [15]:
a + b

array([ 7,  9, 11, 13,  5])

In [16]:
a - b

array([-5, -5, -5, -5,  5])

In [17]:
a * b

array([ 6, 14, 24, 36,  0])

In [18]:
a / b

C:\Users\Admin\AppData\Local\Temp\ipykernel_17952\1286629031.py:1: RuntimeWarning: divide by zero encountered in divide
  a / b


array([0.16666667, 0.28571429, 0.375     , 0.44444444,        inf])

In [19]:
a // b

C:\Users\Admin\AppData\Local\Temp\ipykernel_17952\3774276598.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  a // b


array([0, 0, 0, 0, 0])

In [20]:
a % b

C:\Users\Admin\AppData\Local\Temp\ipykernel_17952\2189094906.py:1: RuntimeWarning: divide by zero encountered in remainder
  a % b


array([1, 2, 3, 4, 0])

# Numpy array indexing & slicing

In [23]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [24]:
a[0]

1

In [25]:
a[4]

5

In [26]:
a[0:4]

array([1, 2, 3, 4])

In [27]:
a[:6]

array([1, 2, 3, 4, 5, 6])

# Numpy array placeholders

In [28]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [34]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

# Numpy 2-D arrays

In [4]:
a = np.array([
    [1,2,3,4,5],           
    [4,5,6,7,6]])
a

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 6]])

In [38]:
a.ndim

2

In [39]:
a.shape

(2, 5)

In [ ]:
a[0]

In [5]:
a[:,:]

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 6]])

In [6]:
a[:,1:3]

array([[2, 3],
       [5, 6]])

# Numpy aggregation function

In [7]:
a = np.array([[1,2,3,4,5],[6,7,8,9,2]])
a

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 2]])

In [8]:
a.max()

9

In [9]:
a.min()

1

In [10]:
a.sum()

47

In [14]:
a.mean()

4.7

In [15]:
a.std()

2.6095976701399777

In [16]:
a.sum(axis=0)

array([ 7,  9, 11, 13,  7])

In [17]:
a.sum(axis=1)

array([15, 32])

In [18]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 1.41421356]])

In [20]:
for row in a:
    print(row)

[1 2 3 4 5]
[6 7 8 9 2]


In [21]:
for row in a.flat:
    print(row)

1
2
3
4
5
6
7
8
9
2


# Bollean Indexing

In [22]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
b = a < 4
b

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [24]:
a[b]

array([0, 1, 2, 3])

In [26]:
a [b] = 1111
a

array([[1111, 1111, 1111],
       [1111,    4,    5],
       [   6,    7,    8]])

# Combining array in numpy

In [27]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [39]:
c = np.arange(3).reshape(3,1)
c

array([[0],
       [1],
       [2]])

In [31]:
np.vstack((a,b))                     # Vertical combining

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [41]:
np.hstack((a,c))                    # Harizontal combining

array([[0, 1, 2, 0],
       [3, 4, 5, 1],
       [6, 7, 8, 2]])

# Spliting array in numpy

In [42]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [54]:
b = np.vsplit(a,3)

In [52]:
b

[array([[0, 1]]), array([[2, 3]]), array([[4, 5]])]

In [53]:
b[0]

array([[0, 1]])

In [56]:
c = np.hsplit(a,2)

In [57]:
c

[array([[0],
        [2],
        [4]]),
 array([[1],
        [3],
        [5]])]

# Converting N-D array in to 1-D array

In [59]:
three_dim = np.arange(15).reshape(5,3)
three_dim

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [60]:
np.ravel(three_dim)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])